FROM golang:1.13

# Create and change to the app directory.
WORKDIR /app

# Retrieve application dependencies.
COPY ./src/go.* ./
RUN go mod download

# Copy local code to the container image.
COPY ./src ./

# Copy the web build
RUN mkdir /app/build
COPY ./build ./build

# Build the binary.
RUN CGO_ENABLED=0 GOOS=linux go build

# Run the web service on container startup.
CMD ["./main"]
